#!/usr/bin/env node
/**
 * Concatenates the core into a single global-scope file for static pages
 * that have no bundler. Not a real bundler — the core is deliberately small
 * enough that a regex-free source transform is honest and reviewable.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
/* Both core modules. A static page with no bundler still has to be able to
 * build a compliant radiogroup, which needs the keyboard helpers — shipping
 * only index.mjs left those sites unable to honour role="radiogroup". */
const source = [
  readFileSync(resolve(root, 'core/index.mjs'), 'utf8'),
  readFileSync(resolve(root, 'core/keyboard.mjs'), 'utf8'),
].join('\n\n');

const body = source
  .replace(/^import[^;]+;$/gm, '')
  .replace(/^export (const|function|let) /gm, '$1 ')
  .replace(/^export \{[^}]*\};?$/gm, '');

/**
 * Derived from the source rather than hand-listed, so a new export cannot be
 * silently missing from the global build — which is exactly what happened when
 * announce() and systemTheme() were added and this list was not updated.
 */
const exported = [...source.matchAll(/^export (?:const|function) (\w+)/gm)].map((m) => m[1]);

const out = `/* brains-a11y core — IIFE build. Generated by scripts/build-iife.mjs; do not edit. */
;(function (global) {
${body}
  global.BrainsA11y = { ${exported.join(', ')} };
})(typeof globalThis !== 'undefined' ? globalThis : this);
`;

mkdirSync(resolve(root, 'dist'), { recursive: true });
writeFileSync(resolve(root, 'dist/brains-a11y.js'), out);
console.log(`dist/brains-a11y.js  ${out.length} bytes`);
